---
- name: Initialize k3s cluster
  hosts: masters[0]
  become: true
  roles:
    - role: k3s_init

- name: Harvest cluster token & VIP check
  hosts: masters[0]
  become: true
  gather_facts: false
  tasks:
    - name: Fetch node token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token_slurp

    - name: Set token fact globally
      ansible.builtin.set_fact:
        global_k3s_token: "{{ node_token_slurp['content'] | b64decode | trim }}"
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['all_k3s'] }}"

    - name: Wait for API Server on VIP
      ansible.builtin.wait_for:
        host: "{{ vip_address }}"
        port: 6443
        timeout: 120
        state: started
      delegate_to: localhost

- name: Join additional nasters
  hosts: masters[1:]
  become: true
  gather_facts: true
  roles:
    - role: k3s_masters

- name: Join workers
  hosts: workers
  become: true
  gather_facts: true
  roles:
    - role: k3s_workers
